### ISSUE TITLE
コンピュータシミュレーション入門【第1版第5刷】

### ISSUE THREAD

**Issue by tadakiken** [ohmsha/MHBooks#1]
コンピュータシミュレーション入門【第1版第5刷】のpage 46のボックス・ミュラー法ですが、
（誤）$\sqrt{-\log_eU_1}$
（正）$\sqrt{-2\log_eU_1}$
ではないでしょうか。

**Comment by tadakiken** [comment]
page 152の表6.5で仕入れ価格と販売価格が設定されていますが、これらのパラメーターは使われていないように思います。

**Comment by kyoHashimoto** [comment]
@tadakiken ご指摘いただき，誠にありがとうございます．いずれもご指摘のとおりです．申し訳ございませんでした．
正誤表に追加いたしました．
https://github.com/ohmsha/MHBooks/tree/master/ComputerSimulation
次回重版にて修正させていただきます．
