### ISSUE TITLE
Python意思決定の数理入門[P75] 

### ISSUE THREAD

**Issue by 223mle** [ohmsha/MHBooks#2]
誤植と思われる部分がありました。<br>
①<br>
P54の13行目<br>
$$\frac{1}{2}\times \frac{1}{2} + 2\times \frac{1}{2} = 1+\frac{1}{4}$$
ではないでしょうか。本書だと1・(1/4)となっています。<br>

②<br>
P75の表3.4<br>
右下の確率は
$$P(\bar{X}|\bar{Y}) \Rightarrow P(\bar{Y}|\bar{X})$$
ではないでしょうか。

**Comment by kyoHashimoto** [comment]
ご指摘いただき，ありがとうございます．誤りがあり，申し訳ございませんでした．

①帯分数の表現を誤っていました。

②ご指摘のとおり，XとYの表記が逆です。

これらを修正したものを，次に記載いたしました。
https://github.com/ohmsha/MHBooks/tree/master/DecisionMaking
